id: P008096
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG24060
  title: བློ་བཟང་དགོངས་རྒྱན་མུ་ཏིག་ཕྲེང་མཛེས་དེབ་སོ་དྲུག་པ།
  author: ''
  volumes:
    dccabdd2ec674e94af893c2900102216:
      image_group_id: I1KG24225
      title: Volume 1 of blo bzang dgongs rgyan mu tig phreng mdzed deb so drug pa/
      volume_number: 1
      total_pages: 280
      base_file: v001.txt
