id: P008096
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24060
  title: བློ་བཟང་དགོངས་རྒྱན་མུ་ཏིག་ཕྲེང་མཛེས་དེབ་སོ་དྲུག་པ།
  author: ''
  volumes:
    a707143189b34f25898b004f6419c3a6:
      image_group_id: I1KG24225
      title: ''
      volume_number: 1
      total_pages: 280
ebook_metadata:
  title: བློ་བཟང་དགོངས་རྒྱན་མུ་ཏིག་ཕྲེང་མཛེས་དེབ་སོ་དྲུག་པ།
  author: ''
  sku: P008096
  cover: cover.jpg
  layers:
  - pagination
